<a href="https://colab.research.google.com/github/Akshathats/Complete-Python-3-Bootcamp/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.2.0


In [ ]:
dataset = pd.read_csv(r"D:\MY_WORK\Pincore\VIP\VIP-Pincore\Dataset\week3\ANN\Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values  # [ rows, colums ] : --> entire colums rows
Y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(Y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()     #initializing the ANN

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))    #adding the input layer 

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) #adding the 1st hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))    #adding the output layer 

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy' , metrics =['accuracy'])    #compiling the ANN

In [ ]:
ann.fit(X_train, Y_train, batch_size = 32 , epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6373 - accuracy: 0.6327
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4845 - accuracy: 0.7954
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4568 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4418 - accuracy: 0.7984
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4315 - accuracy: 0.8050
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.8150
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4154 - accuracy: 0.8204
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4082 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8301
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3933 - accura

In [ ]:
ann.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  78        
_________________________________________________________________
dense_1 (Dense)              multiple                  42        
_________________________________________________________________
dense_2 (Dense)              multiple                  7         
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [ ]:
y_pred = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
if (y_pred > 0.5) :   # depends based on the banks 
    print(" The customer will leave the bank")
else:
    print(" The customer will stay with the bank")

 The customer will stay with the bank


In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)*100

[[1501   94]
 [ 192  213]]


85.7